version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0 # Primary container, where commands are run
      
        auth:
          username: mydockerhub-user
           password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - run: echo "Hello world!"
