version 2.1
jobs:
  build-android:
    docker:
      - image: cimg/android:2021.10.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      steps:
        - checkout
        - run: echo "Hello World!"
  build-linux:
    docker:
      - image: cimg/node:17.2.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      steps:
        - checkout
        - run: echo "Hello Linux!"
